FROM node:22-alpine
WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true

COPY package.json package-lock.json ./
RUN sed -i '/@next\/swc-win32-x64-msvc/d' package.json
RUN npm ci

EXPOSE 3000

CMD ["npm", "run", "dev"]
